from __future__ import annotations

from pathlib import Path

import pandas as pd

from support_reply_assistant.policies import load_policy_sections, retrieve_policy_sections


ROOT = Path(__file__).resolve().parent


def expected_policy_ids(raw: str) -> list[str]:
    return [item.strip() for item in str(raw).split("|") if item.strip()]


def build_query(row: pd.Series) -> str:
    return "\n".join(
        [
            str(row["customer_ticket"]),
            f"account tier {row['account_tier']}",
            f"ownership verified {row['ownership_verified']}",
        ]
    )


def to_markdown_table(df: pd.DataFrame) -> str:
    headers = list(df.columns)
    rows = [headers]
    for _, row in df.iterrows():
        rows.append([str(value) for value in row.tolist()])

    widths = [max(len(row[i]) for row in rows) for i in range(len(headers))]
    header = "| " + " | ".join(rows[0][i].ljust(widths[i]) for i in range(len(headers))) + " |"
    divider = "| " + " | ".join("-" * widths[i] for i in range(len(headers))) + " |"
    body = [
        "| " + " | ".join(row[i].ljust(widths[i]) for i in range(len(headers))) + " |"
        for row in rows[1:]
    ]
    return "\n".join([header, divider, *body])


def main() -> None:
    cases = pd.read_csv(ROOT / "data" / "test_tickets.csv")
    sections = load_policy_sections(ROOT / "data" / "policy_handbook.md")

    audit_rows = []
    for _, row in cases.iterrows():
        retrieved = retrieve_policy_sections(build_query(row), sections, top_k=3)
        retrieved_ids = [section.policy_id for section in retrieved]
        expected_ids = expected_policy_ids(row["expected_policy_ids"])
        coverage = all(policy_id in retrieved_ids for policy_id in expected_ids)
        audit_rows.append(
            {
                "case_id": row["case_id"],
                "expected_policy_ids": "|".join(expected_ids),
                "retrieved_policy_ids": "|".join(retrieved_ids),
                "covered": coverage,
            }
        )

    audit_df = pd.DataFrame(audit_rows)
    coverage_rate = audit_df["covered"].mean()

    csv_path = ROOT / "artifacts" / "retrieval_audit.csv"
    md_path = ROOT / "artifacts" / "retrieval_audit.md"

    audit_df.to_csv(csv_path, index=False)

    lines = [
        "# Retrieval Audit",
        "",
        "This file is generated by `python audit_retrieval.py`.",
        "",
        f"Coverage on the synthetic evaluation set: **{int(audit_df['covered'].sum())}/{len(audit_df)}** "
        f"cases ({coverage_rate:.0%}).",
        "",
        to_markdown_table(audit_df),
    ]
    md_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
