from __future__ import annotations

from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

from support_reply_assistant.evaluation import score_reply
from support_reply_assistant.policies import load_policy_sections
from support_reply_assistant.schemas import TicketContext
from support_reply_assistant.workflows import generate_baseline_reply, generate_grounded_reply


ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    grouped = df.groupby("workflow").agg(
        cases=("case_id", "count"),
        avg_score=("score", "mean"),
        risk_accuracy=("risk_match", "mean"),
        escalation_accuracy=("escalation_match", "mean"),
        target_accuracy=("target_match", "mean"),
        citation_accuracy=("citation_match", "mean"),
        refund_safety=("auto_promise_refund_fail", lambda s: 1 - s.mean()),
    )
    return grouped.reset_index()


def to_markdown_table(df: pd.DataFrame) -> str:
    headers = list(df.columns)
    rows = [headers]
    for _, row in df.iterrows():
        formatted = []
        for value in row.tolist():
            if isinstance(value, float):
                formatted.append(f"{value:.3f}")
            else:
                formatted.append(str(value))
        rows.append(formatted)

    widths = [max(len(str(row[i])) for row in rows) for i in range(len(headers))]
    header_line = "| " + " | ".join(str(value).ljust(widths[i]) for i, value in enumerate(rows[0])) + " |"
    divider = "| " + " | ".join("-" * widths[i] for i in range(len(widths))) + " |"
    body = [
        "| " + " | ".join(str(value).ljust(widths[i]) for i, value in enumerate(row)) + " |"
        for row in rows[1:]
    ]
    return "\n".join([header_line, divider, *body])


def main() -> None:
    cases = pd.read_csv(ROOT / "data" / "test_tickets.csv")
    policy_sections = load_policy_sections(ROOT / "data" / "policy_handbook.md")

    rows: list[dict] = []
    for _, row in cases.iterrows():
        context = TicketContext(
            customer_ticket=row["customer_ticket"],
            account_tier=row["account_tier"],
            ownership_verified=bool(row["ownership_verified"]),
        )

        baseline = generate_baseline_reply(context)
        grounded, _ = generate_grounded_reply(context, policy_sections)

        for workflow_name, reply in [("baseline", baseline), ("grounded", grounded)]:
            result = score_reply(row, reply)
            rows.append(
                {
                    "case_id": row["case_id"],
                    "workflow": workflow_name,
                    "risk_match": result.risk_match,
                    "escalation_match": result.escalation_match,
                    "target_match": result.target_match,
                    "citation_match": result.citation_match,
                    "auto_promise_refund_fail": result.auto_promise_refund_fail,
                    "score": result.score,
                    "draft_reply": reply.draft_reply,
                    "internal_notes": reply.internal_notes,
                    "risk_level": reply.risk_level,
                    "escalation_required": reply.escalation_required,
                    "escalation_target": reply.escalation_target,
                    "cited_policy_ids": "|".join(reply.cited_policy_ids),
                }
            )

    details = pd.DataFrame(rows)
    summary = summarize(details)

    details_path = ROOT / "artifacts" / "eval_cases.csv"
    summary_path = ROOT / "artifacts" / "eval_summary.csv"
    markdown_path = ROOT / "artifacts" / "eval_summary.md"

    details.to_csv(details_path, index=False)
    summary.to_csv(summary_path, index=False)

    markdown_lines = [
        "# Evaluation Summary",
        "",
        "This file is generated by `python evaluate.py`.",
        "",
        to_markdown_table(summary),
        "",
        "Interpretation notes:",
        "- `risk_accuracy` checks exact-match risk labels.",
        "- `escalation_accuracy` checks whether escalation was required.",
        "- `target_accuracy` checks the escalation queue.",
        "- `citation_accuracy` checks whether expected handbook policy IDs were cited.",
        "- `refund_safety` penalizes out-of-policy refund promises.",
    ]
    markdown_path.write_text("\n".join(markdown_lines), encoding="utf-8")

    print(f"Wrote {details_path}")
    print(f"Wrote {summary_path}")
    print(f"Wrote {markdown_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        raise SystemExit(
            f"Evaluation failed: {exc}\n\n"
            "Make sure you have copied .env.example to .env and set GOOGLE_API_KEY before running evaluate.py."
        )
